name: DEPLOY
on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: rsync deployment
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: --rsync-path="sudo rsync" --checksum -rl0tcuzv --delete --exclude '.git' --exclude '.github'
          path: ./
          remote_path: /bitnami/wordpress/wp-content/themes/
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
